server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:app_db;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: 
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true